import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { NETWORK_CONFIG } from '../assets/data/network.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const MANIFEST_PATH = path.join(ROOT, 'assets/vendor-manifest.json');
const AVAILABLE_FLAGS_PATH = path.join(ROOT, 'assets/js/lib/available-flags.js');
const UPDATE_LOCK = process.argv.includes('--update-lock');
const CODE_PATTERN = /^[A-Z]{2}$/;

function fail(message) {
  throw new Error(message);
}

function countryCodes() {
  if (NETWORK_CONFIG?.partnersBlock?.visible === false) return [];
  const partners = NETWORK_CONFIG?.partnersBlock?.partners || [];
  const codes = partners.map(partner => partner.country);
  for (const code of codes) {
    if (typeof code !== 'string' || !CODE_PATTERN.test(code)) {
      fail(`Invalid ISO alpha-2 country code in generated network data: ${String(code)}`);
    }
  }
  return [...new Set(codes)].sort();
}

function pngDimensions(buffer, label) {
  const signature = '89504e470d0a1a0a';
  if (
    buffer.length < 24
    || buffer.subarray(0, 8).toString('hex') !== signature
    || buffer.subarray(12, 16).toString('ascii') !== 'IHDR'
  ) {
    fail(`${label} is not a valid PNG`);
  }
  return [buffer.readUInt32BE(16), buffer.readUInt32BE(20)];
}

function sha256(buffer) {
  return createHash('sha256').update(buffer).digest('hex');
}

function availableFlagsModule(codes) {
  const rows = codes.map(code => `  '${code}',`).join('\n');
  return `// Generated by scripts/vendor-flags.mjs --update-lock.\nexport const AVAILABLE_FLAG_CODES = Object.freeze([\n${rows}\n]);\n`;
}

async function readManifest() {
  return JSON.parse(await readFile(MANIFEST_PATH, 'utf8'));
}

async function localFlagEntry(code, size, dimensions) {
  const relativePath = `assets/flags/${size}/${code.toLowerCase()}.png`;
  const absolutePath = path.join(ROOT, relativePath);
  const buffer = await readFile(absolutePath).catch(() => fail(`Missing local flag: ${relativePath}`));
  const actualDimensions = pngDimensions(buffer, relativePath);
  if (actualDimensions[0] !== dimensions[0] || actualDimensions[1] !== dimensions[1]) {
    fail(`${relativePath} is ${actualDimensions.join('x')}; expected ${dimensions.join('x')}`);
  }
  return {
    path: relativePath,
    source: `https://flagcdn.com/${size}/${code.toLowerCase()}.png`,
    size: buffer.length,
    sha256: sha256(buffer),
    width: dimensions[0],
    height: dimensions[1],
  };
}

async function downloadFlag(code, size, dimensions) {
  const url = `https://flagcdn.com/${size}/${code.toLowerCase()}.png`;
  const response = await fetch(url, { redirect: 'follow' });
  if (!response.ok) fail(`${url} returned HTTP ${response.status}`);
  const buffer = Buffer.from(await response.arrayBuffer());
  const actualDimensions = pngDimensions(buffer, url);
  if (actualDimensions[0] !== dimensions[0] || actualDimensions[1] !== dimensions[1]) {
    fail(`${url} is ${actualDimensions.join('x')}; expected ${dimensions.join('x')}`);
  }
  const directory = path.join(ROOT, 'assets/flags', size);
  await mkdir(directory, { recursive: true });
  await writeFile(path.join(directory, `${code.toLowerCase()}.png`), buffer);
}

async function main() {
  const manifest = await readManifest();
  const flags = manifest.dependencies?.flags;
  if (!flags?.sizes) fail('Flag configuration is missing from assets/vendor-manifest.json');

  const codes = countryCodes();
  const sizeEntries = Object.entries(flags.sizes);

  if (UPDATE_LOCK) {
    for (const code of codes) {
      for (const [size, dimensions] of sizeEntries) {
        await downloadFlag(code, size, dimensions);
      }
    }
  }

  const entries = [];
  for (const code of codes) {
    for (const [size, dimensions] of sizeEntries) {
      entries.push(await localFlagEntry(code, size, dimensions));
    }
  }

  if (UPDATE_LOCK) {
    flags.countryCodes = codes;
    flags.files = entries;
    await writeFile(MANIFEST_PATH, `${JSON.stringify(manifest, null, 2)}\n`);
    await writeFile(AVAILABLE_FLAGS_PATH, availableFlagsModule(codes));
    console.log(`Updated ${entries.length} locked flag assets for ${codes.length} countries.`);
    return;
  }

  if (JSON.stringify(flags.countryCodes) !== JSON.stringify(codes)) {
    fail('Generated network countries differ from the vendor lock; run npm run vendor:flags -- --update-lock');
  }
  if (JSON.stringify(flags.files) !== JSON.stringify(entries)) {
    fail('Local flag bytes differ from assets/vendor-manifest.json; review and update the lock explicitly');
  }
  const expectedModule = availableFlagsModule(codes);
  const actualModule = await readFile(AVAILABLE_FLAGS_PATH, 'utf8');
  if (actualModule !== expectedModule) fail('available-flags.js is out of sync with the vendor lock');

  console.log(`Verified ${entries.length} locked flag assets for ${codes.length} countries.`);
}

main().catch(error => {
  console.error(`Flag vendorization failed: ${error.message}`);
  process.exitCode = 1;
});
